version: '3'

services:

  logstash:
    command: /usr/share/plugins/plugin/.ci/logstash-run.sh
    environment:
        - INTEGRATION=${INTEGRATION:-false}
        - SECURE_INTEGRATION=${SECURE_INTEGRATION:-false}

  opensearch:
    build:
      context: ../
      dockerfile: .ci/Dockerfile.opensearch
      args:
        - OPENSEARCH_VERSION=$OPENSEARCH_VERSION
        - INTEGRATION=${INTEGRATION:-false}
        - SECURE_INTEGRATION=${SECURE_INTEGRATION:-false}
    command: /usr/share/opensearch/opensearch-run.sh
    tty: true
    ports:
      - "9200:9200"
    user: opensearch

